import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import imageLoader from '../../imageLoader'

export default function CharacterPage( { character }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>this is character page</h1>


     <div key={character.id}>
          {character.name}
          <Image 
          loader={imageLoader}
           src={character.image}
           alt={character.image}
           width="200"
           height="200"
          />

        </div>

    </div>
  )
}

export const getStaticPaths = async () => {
  const response = await fetch('https://rickandmortyapi.com/api/character')
  const { results } = await response.json();

  return {
    paths: results.map((character) => {
        return {
            params: {
                id: String(character.id)
            }
        }

    }),
    fallback: false
  }

}

export const getStaticProps = async ({ params } ) => {
  const response = await fetch(`https://rickandmortyapi.com/api/character/${params.id}`)
  const result = await response.json();
  console.log('character is', result)

  return {
    props: {
      character: result
    }
  }

}

export const getServerSideProps = async ({ context } ) => {
    const response = await fetch(`https://rickandmortyapi.com/api/character/${context.query.id}`)
    const result = await response.json();
    console.log('character is', result)
  
    return {
      props: {
        character: result
      }
    }
  
  }