import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import imageLoader from '../imageLoader'

export default function Home( { characters }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>this is home page</h1>
      {/* {JSON.stringify(characters)} */}
      {characters.map((character) => {
        
        return <div key={character.id}>
          <Link href={`/characters/${character.id}`}>
            <a> {character.name}</a>
         
          </Link>
         
          <Image 
          loader={imageLoader}
           src={character.image}
           alt={character.image}
           width="200"
           height="200"
          />

        </div>


      })}

    </div>
  )
}

export const getStaticProps = async () => {
  const response = await fetch('https://rickandmortyapi.com/api/character')
  const { results } = await response.json();

  return {
    props: {
      characters: results
    }
  }

}